package org.jbpm.demo.itorders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Survey implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean satisfied;
   private java.lang.Boolean deliveredOnTime;
   private java.lang.String missingEquipment;
   private java.lang.String comment;

   public Survey()
   {
   }

   public java.lang.Boolean getSatisfied()
   {
      return this.satisfied;
   }

   public void setSatisfied(java.lang.Boolean satisfied)
   {
      this.satisfied = satisfied;
   }

   public java.lang.Boolean getDeliveredOnTime()
   {
      return this.deliveredOnTime;
   }

   public void setDeliveredOnTime(java.lang.Boolean deliveredOnTime)
   {
      this.deliveredOnTime = deliveredOnTime;
   }

   public java.lang.String getMissingEquipment()
   {
      return this.missingEquipment;
   }

   public void setMissingEquipment(java.lang.String missingEquipment)
   {
      this.missingEquipment = missingEquipment;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public Survey(java.lang.Boolean satisfied,
         java.lang.Boolean deliveredOnTime,
         java.lang.String missingEquipment, java.lang.String comment)
   {
      this.satisfied = satisfied;
      this.deliveredOnTime = deliveredOnTime;
      this.missingEquipment = missingEquipment;
      this.comment = comment;
   }

}