package org.jbpm.demo.itorders.services;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ITOrderService implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ITOrderService() {
    }

    public String printMessage(String text) {
        String message = "Message received :: " + text + "!";
        System.out.println(message);
        return message;
    }

}